related/member-portal-agent/mdapi/NFCU_Member_Portal_Agent/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Balance_Transfer_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Balance Transfer Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Citizenship_Status__c</fullName>
        <label>Citizenship Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>U.S. Citizen</fullName>
                </value>
                <value>
                    <fullName>Permanent Resident</fullName>
                </value>
                <value>
                    <fullName>Non-Permanent Resident</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_of_Citizenship__c</fullName>
        <label>Country of Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_of_Dual_Citizenship__c</fullName>
        <label>Country of Dual Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <label>Country of Primary Residence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Different_Statement_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Statements Sent to Different Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dual_Citizenship__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dual Citizenship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <label>Company Name or Employer</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <label>Employment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employed</fullName>
                </value>
                <value>
                    <fullName>Homemaker</fullName>
                </value>
                <value>
                    <fullName>Permanently Disabled</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Self-Employed</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Unemployed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Existing_Accounts__c</fullName>
        <label>Existing Accounts</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gross_Annual_Income__c</fullName>
        <label>Total Gross Annual Income</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Housing_Payment__c</fullName>
        <label>Monthly Housing Payment</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mothers_Maiden_Name__c</fullName>
        <label>Mother&apos;s Maiden Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Balances__c</fullName>
        <label>Number of Balances to Transfer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accountant</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Programmer/Developer</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>Teacher</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Contact_Number__c</fullName>
        <label>Primary Contact Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Phone_Type__c</fullName>
        <label>Primary Phone Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile phone</fullName>
                </value>
                <value>
                    <fullName>Home phone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_of_Income__c</fullName>
        <label>Source of Income</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Employment Income</fullName>
                </value>
                <value>
                    <fullName>Inheritance/Trust</fullName>
                </value>
                <value>
                    <fullName>Investment Income</fullName>
                </value>
                <value>
                    <fullName>Retirement Income</fullName>
                </value>
                <value>
                    <fullName>Social Security</fullName>
                </value>
                <value>
                    <fullName>Unemployment/Other Income</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>Social Security Number</label>
        <length>11</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Jr.</fullName>
                </value>
                <value>
                    <fullName>Sr.</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
                <value>
                    <fullName>III</fullName>
                </value>
                <value>
                    <fullName>IV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>US_Citizen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>US Citizen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Years_in_Occupation__c</fullName>
        <label>Years in Occupation</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>ZIP Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
</CustomObject>

related/card-application-actions/force-app/main/default/classes/CardDocumentAIService.cls
/**
 * CardDocumentAIService
 * Uses the Agentforce Models API (aiplatform.ModelsAPI) to extract structured
 * application field values from an uploaded document's text. Returns a JSON string
 * keyed by Application__c field API names, which the LWC merges into the form for
 * the user to review before submitting.
 *
 * PREREQUISITE: Einstein Generative AI must be enabled and the running user must
 * have the "Einstein Generative AI User" permission set. If your org does not have
 * this feature, remove this class and the cardDocumentUpload usage before deploying.
 */
public with sharing class CardDocumentAIService {

    private static final String MODEL = 'sfdc_ai__DefaultOpenAIGPT4OmniMini';

    // Field API names the model is allowed to populate (kept in sync with the object).
    private static final String FIELD_LIST =
        'First_Name__c, Middle_Name__c, Last_Name__c, Suffix__c, Address_Line_1__c, ' +
        'Address_Line_2__c, City__c, State__c, Zip_Code__c, Country_of_Residence__c, ' +
        'Different_Statement_Address__c, Primary_Contact_Number__c, Primary_Phone_Type__c, ' +
        'Email__c, SSN__c, Date_of_Birth__c, Mothers_Maiden_Name__c, US_Citizen__c, ' +
        'Country_of_Citizenship__c, Citizenship_Status__c, Dual_Citizenship__c, ' +
        'Country_of_Dual_Citizenship__c, Existing_Accounts__c, Employment_Status__c, ' +
        'Occupation__c, Employer__c, Years_in_Occupation__c, Work_Phone__c, ' +
        'Gross_Annual_Income__c, Source_of_Income__c, Monthly_Housing_Payment__c, ' +
        'Balance_Transfer_Requested__c, Number_of_Balances__c, Transfer_Institution__c, ' +
        'Transfer_Account_Number__c, Transfer_Requested_Amount__c, Add_Authorized_User__c, ' +
        'Card_Product_Name__c';

    @AuraEnabled
    public static String extractFields(String documentText) {
        if (String.isBlank(documentText)) {
            throw new AuraHandledException('No document text was provided to parse.');
        }

        String prompt =
            'You are a data-extraction assistant for a credit card application. ' +
            'Read the DOCUMENT below and extract any values that map to these Salesforce ' +
            'field API names:\n' + FIELD_LIST + '\n\n' +
            'Rules:\n' +
            '- Return ONLY a single JSON object. No prose, no code fences.\n' +
            '- Use the exact field API names above as keys.\n' +
            '- Omit any field you cannot confidently determine.\n' +
            '- Dates must be formatted YYYY-MM-DD.\n' +
            '- Currency/number fields must be plain numbers (no $ or commas): ' +
            'Gross_Annual_Income__c, Monthly_Housing_Payment__c, Transfer_Requested_Amount__c, Years_in_Occupation__c.\n' +
            '- Boolean fields must be true or false: US_Citizen__c, Dual_Citizenship__c, ' +
            'Different_Statement_Address__c, Balance_Transfer_Requested__c, Add_Authorized_User__c.\n' +
            '- Existing_Accounts__c is a semicolon-separated list from: Checking, Savings, None.\n' +
            '- Picklists must match these options exactly:\n' +
            '  Suffix__c: Jr., Sr., II, III, IV\n' +
            '  Primary_Phone_Type__c: Mobile phone, Home phone\n' +
            '  Citizenship_Status__c: U.S. Citizen, Permanent Resident, Non-Permanent Resident, Other\n' +
            '  Employment_Status__c: Employed, Homemaker, Permanently Disabled, Retired, Self-Employed, Student, Unemployed\n' +
            '  Occupation__c: Accountant, Architect, Programmer/Developer, Engineer, Teacher, Nurse, Physician, Manager, Sales, Consultant, Attorney, Other\n' +
            '  Source_of_Income__c: Employment Income, Inheritance/Trust, Investment Income, Retirement Income, Social Security, Unemployment/Other Income\n' +
            '  Number_of_Balances__c: 1, 2, 3\n' +
            '  Transfer_Institution__c: Chase, Citi, Capital One, Discover, American Express, Wells Fargo, U.S. Bank, Other\n' +
            '  State__c / Country fields: full names (e.g. Colorado, United States).\n\n' +
            'DOCUMENT:\n' + documentText;

        try {
            aiplatform.ModelsAPI.createGenerations_Request request =
                new aiplatform.ModelsAPI.createGenerations_Request();
            request.modelName = MODEL;

            aiplatform.ModelsAPI_GenerationRequest genRequest =
                new aiplatform.ModelsAPI_GenerationRequest();
            genRequest.prompt = prompt;
            request.body = genRequest;

            aiplatform.ModelsAPI.createGenerations_Response response =
                new aiplatform.ModelsAPI().createGenerations(request);

            if (response.Code200 != null &&
                response.Code200.generation != null) {
                return cleanJson(response.Code200.generation.generatedText);
            }
            throw new AuraHandledException('The AI model returned no response.');
        } catch (AuraHandledException e) {
            throw e;
        } catch (Exception e) {
            throw new AuraHandledException('Document parsing failed: ' + e.getMessage());
        }
    }

    @TestVisible
    private static String cleanJson(String raw) {
        if (String.isBlank(raw)) {
            return '{}';
        }
        String t = raw.trim();
        if (t.startsWith('```')) {
            t = t.replaceFirst('(?s)^```[a-zA-Z]*\\s*', '');
            if (t.endsWith('```')) {
                t = t.substring(0, t.length() - 3);
            }
            t = t.trim();
        }
        Integer first = t.indexOf('{');
        Integer last = t.lastIndexOf('}');
        if (first >= 0 && last > first) {
            t = t.substring(first, last + 1);
        }
        return t;
    }
}